# File automatically-generated by STM32CubeMX - Do not modify
cmake_minimum_required(VERSION 3.22)
# STM32CubeMX generated symbols (macros)
set(MX_Defines_Syms 
	CORE_CM7 
	USE_HAL_DRIVER 
	STM32H747xx 
	USE_PWR_DIRECT_SMPS_SUPPLY
    $<$<CONFIG:Debug>:DEBUG>
)
# STM32CubeMX generated include paths
set(MX_Include_Dirs
    ${CMAKE_CURRENT_SOURCE_DIR}/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS/Device/ST/STM32H7xx/Include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS/Include

    # CMSIS-DSP Library
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS-DSP-main/Include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS-DSP-main/PrivateInclude

    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/Components/Common
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/Components/nt35510
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/STM32H747I-DISCO

    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/Components/wm8994

    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/ST/STM32_Audio/Addons/PDM/Inc

    ${CMAKE_CURRENT_SOURCE_DIR}/../Utilities
)
# STM32CubeMX generated application sources
set(MX_Application_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/main.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/stm32_init.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/audio_effects_mode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/pitch_detection_mode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/spectrum_analyzer_mode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/spectrum_display.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/lcd_utils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/guitar_tuning.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/stm32h7xx_it.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/stm32h7xx_hal_msp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/sysmem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/syscalls.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Startup/startup_stm32h747xx_CM7.s
)

# CMSIS-DSP Library Sources (using aggregate source files)
set(CMSIS_DSP_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS-DSP-main/Source/CommonTables/CommonTables.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS-DSP-main/Source/TransformFunctions/TransformFunctions.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS-DSP-main/Source/ComplexMathFunctions/ComplexMathFunctions.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS-DSP-main/Source/StatisticsFunctions/StatisticsFunctions.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS-DSP-main/Source/BasicMathFunctions/BasicMathFunctions.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS-DSP-main/Source/FastMathFunctions/FastMathFunctions.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS-DSP-main/Source/SupportFunctions/SupportFunctions.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS-DSP-main/Source/FilteringFunctions/FilteringFunctions.c
)

# STM32 HAL/LL Drivers
set(STM32_Drivers_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/../Common/Src/system_stm32h7xx_dualcore_boot_cm4_cm7.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c

    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dsi.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma2d.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sdram.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_fmc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai_ex.c
    
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/Components/nt35510/nt35510.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/Components/nt35510/nt35510_reg.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/Components/is42s32800j/is42s32800j.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/Components/otm8009a/otm8009a.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/Components/otm8009a/otm8009a_reg.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/Components/wm8994/wm8994.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/Components/wm8994/wm8994_reg.c
    
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/STM32H747I-DISCO/stm32h747i_discovery.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/STM32H747I-DISCO/stm32h747i_discovery_bus.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/STM32H747I-DISCO/stm32h747i_discovery_lcd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/STM32H747I-DISCO/stm32h747i_discovery_sdram.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/BSP/STM32H747I-DISCO/stm32h747i_discovery_audio.c

    ${CMAKE_CURRENT_SOURCE_DIR}/../Utilities/stm32_lcd.c
    
)

# Drivers Midllewares

# Link directories setup
set(MX_LINK_DIRS
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/ST/STM32_Audio/Addons/PDM/Lib
)
# Project libraries
set (MX_LINK_LIBS 
    STM32_Drivers
    CMSIS_DSP
    ${TOOLCHAIN_LINK_LIBRARIES}
    PDMFilter_CM7_GCC_wc16
)
# Interface library for includes and symbols
add_library(stm32cubemx INTERFACE)
target_include_directories(stm32cubemx INTERFACE ${MX_Include_Dirs})
target_compile_definitions(stm32cubemx INTERFACE ${MX_Defines_Syms})

# Create STM32_Drivers static library
add_library(STM32_Drivers OBJECT)
target_sources(STM32_Drivers PRIVATE ${STM32_Drivers_Src})
target_link_libraries(STM32_Drivers PUBLIC stm32cubemx)

# Create CMSIS-DSP static library
add_library(CMSIS_DSP OBJECT)
target_sources(CMSIS_DSP PRIVATE ${CMSIS_DSP_Src})
target_compile_definitions(CMSIS_DSP PRIVATE ARM_MATH_CM7 __FPU_PRESENT=1)
target_link_libraries(CMSIS_DSP PUBLIC stm32cubemx)


# Add STM32CubeMX generated application sources to the project
target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${MX_Application_Src})

# Link directories setup
target_link_directories(${CMAKE_PROJECT_NAME} PRIVATE ${MX_LINK_DIRS})

# Add libraries to the project
target_link_libraries(${CMAKE_PROJECT_NAME} ${MX_LINK_LIBS})

# Add the map file to the list of files to be removed with 'clean' target
set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES ADDITIONAL_CLEAN_FILES ${CMAKE_PROJECT_NAME}.map)


# Validate that STM32CubeMX code is compatible with C standard
if((CMAKE_C_STANDARD EQUAL 90) OR (CMAKE_C_STANDARD EQUAL 99))
    message(ERROR "Generated code requires C11 or higher")
endif()